import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "de" | "sk";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.about": "About",
    "nav.product": "Product",
    "nav.whyWinso": "Why WINSO",
    "nav.team": "Team",
    "nav.contact": "Contact Us",

    // Hero
    "hero.badge": "Hybrid is Simply Better",
    "hero.headline": "WINSO –",
    "hero.headlineHighlight": "Hybrid is Simply Better",
    "hero.subheadline": "At WINSO, we aim to make renewable energy simpler, smarter, and more efficient. Our turbine combines wind and solar power into one hybrid system that produces stable energy even when weather conditions change.",
    "hero.learnMore": "Learn More",
    "hero.contactUs": "Contact Us",
    "hero.yearsExp": "Years of",
    "hero.experience": "Experience",
    "hero.cleanEnergy": "Clean",
    "hero.energy": "Energy",
    "hero.designed": "Designed &",
    "hero.manufactured": "Manufactured",

    // About
    "about.badge": "About WINSO",
    "about.headline": "Technology That",
    "about.headlineHighlight": "Adapts",
    "about.p1": "At WINSO, we aim to make renewable energy simpler, smarter, and more efficient. Our turbine combines wind and solar power into one hybrid system that produces stable energy even when weather conditions change.",
    "about.p2": "We believe the future of energy lies in technology that adapts, not waits. That's why WINSO uses solar-powered motor support, flexible solar blades, and intelligent control systems to keep performance high at all times. Thanks to its compact and integrated design, the system also requires significantly less space compared to traditional separate solutions.",
    "about.p3": "Our vision is clear: deliver reliable clean energy anywhere, with a system that works day and night — and moves renewable power a step forward.",
    "about.feature1": "Solar-powered motor support",
    "about.feature2": "Flexible solar blades",
    "about.feature3": "Intelligent control systems",
    "about.appTitle": "Perfect for Every Application",
    "about.app1": "Private Households",
    "about.app2": "Garden Houses",
    "about.app3": "Island Applications",
    "about.app4": "Vacation Homes",
    "about.app5": "Mobile Homes",
    "about.app6": "Boats & Yachts",
    "about.appDesc1": "Power your home, reduce electricity costs, and stay independent with a stable hybrid wind-solar system.",
    "about.appDesc2": "Run lighting, tools, and small appliances with an off-grid system that generates and stores its own energy.",
    "about.appDesc3": "Stay fully independent in remote areas with a hybrid turbine designed for continuous, reliable energy generation.",
    "about.appDesc4": "Keep your holiday home powered year-round with a low-maintenance system that works in changing conditions.",
    "about.appDesc5": "Produce clean energy on the go with a compact system built for mobility and efficient battery charging.",
    "about.appDesc6": "Power onboard systems using wind and solar energy combined in a space-efficient hybrid solution.",

    // Product
    "product.badge": "Our Mission",
    "product.headline": "The",
    "product.headlineHighlight": "WINSO",
    "product.headlineEnd": "Turbine",
    "product.intro": "Introducing our WINSO turbine—a hybrid wind-solar system that matches, and even exceeds, the performance of horizontal wind turbines. Solar cells integrated directly into the rotor blades power an electric motor that provides additional drive, meaning no extra space is required.",
    "product.techTitle": "Technically Well Thought Out",
    "product.techP1": "This electric boost also enables continuous energy production in low-wind conditions, contributing up to 30% of the total output and significantly increasing daily energy yield.",
    "product.techP2": "The wind blades are mounted on movable supports that respond to centrifugal forces. At high rotational speeds, they shift into a closed oval configuration, reducing wind impact on the blades. This prevents the system from overspeeding while eliminating headwind resistance—ensuring safer, more efficient operation overall.",
    "product.benefit1": "Solar cells integrated directly into rotor blades",
    "product.benefit2": "Electric motor for continuous low-wind operation",
    "product.benefit3": "Movable supports prevent dangerous overspeeding",
    "product.benefit4": "Closed oval configuration reduces wind impact at high speeds",
    "product.benefit5": "Eliminates headwind resistance for safer operation",
    "product.requestQuote": "Request a Quote",
    "product.output": "Output",
    "product.hybrid": "Hybrid",
    "product.technology": "Technology",
    "product.feat1Title": "Hybrid Design",
    "product.feat1Desc": "Wind-solar integration with solar cells built directly into the rotor blades.",
    "product.feat2Title": "Superior Efficiency",
    "product.feat2Desc": "Matches and exceeds horizontal turbine performance with electric boost capability.",
    "product.feat3Title": "Low-Wind Operation",
    "product.feat3Desc": "Electric motor provides additional drive in low-wind conditions for consistent output.",
    "product.feat4Title": "Space Efficient",
    "product.feat4Desc": "No extra space required—solar integration means everything in one compact unit.",
    "product.feat5Title": "Cost-Effective",
    "product.feat5Desc": "Not significantly more expensive than traditional vertical turbines.",
    "product.feat6Title": "Smart Safety",
    "product.feat6Desc": "Movable blade supports prevent overspeeding while eliminating headwind resistance.",

    // Business Model
    "business.badge": "Business Model",
    "business.headline": "Simple and",
    "business.headlineHighlight": "Scalable",
    "business.p1": "Our business model is simple and scalable. Our goal is to manufacture wind turbines cost-effectively through in-house production. The WINSO turbine is not significantly more expensive than a traditional vertical turbine.",
    "business.p2": "Through an initially lean offering, we can provide our product more efficiently and at a lower cost than comparable performance models on the market. Focusing on one-time sales allows us to achieve stable and recurring revenue with growth potential.",
    "business.pillar1Title": "In-House Manufacturing",
    "business.pillar1Desc": "Cost-effective production through complete manufacturing control.",
    "business.pillar2Title": "Lean Product Line",
    "business.pillar2Desc": "Initially lean offering for efficiency and lower costs than comparable models.",
    "business.pillar3Title": "Scalable Model",
    "business.pillar3Desc": "Simple structure designed to scale with growing market demand.",
    "business.pillar4Title": "Recurring Revenue",
    "business.pillar4Desc": "One-time sales foundation with stable, recurring revenue and growth potential.",
    "business.approach": "Our Approach",
    "business.costEffective": "Cost",
    "business.effectiveProd": "Effective",
    "business.production": "Production",
    "business.lean": "Lean",
    "business.initial": "Initial",
    "business.offering": "Offering",

    // Why WINSO
    "why.badge": "Why Choose Us",
    "why.headline": "Why Choose",
    "why.headlineHighlight": "WINSO",
    "why.subheadline": "When it comes to small wind power, WINSO delivers on every front. Here's what sets us apart from the competition.",
    "why.benefit1Title": "Maximum Efficiency",
    "why.benefit1Desc": "Our hybrid design captures more wind energy than traditional turbines, giving you more power from every breeze.",
    "why.benefit2Title": "Built to Last",
    "why.benefit2Desc": "Engineered with premium materials and rigorous testing for 20+ years of reliable operation.",
    "why.benefit3Title": "Affordable Excellence",
    "why.benefit3Desc": "Competitive pricing without cutting corners. True value that pays for itself over time.",
    "why.benefit4Title": "Modern Engineering",
    "why.benefit4Desc": "Cutting-edge technology meets practical design. Smart features that simplify your life.",
    "why.benefit5Title": "Expert Team",
    "why.benefit5Desc": "Backed by decades of combined experience in business, sales, and electrical engineering.",
    "why.benefit6Title": "Quality Guaranteed",
    "why.benefit6Desc": "Every turbine is tested and certified to meet the highest European standards.",
    "why.cta": "Ready to power your future with clean, efficient wind energy?",
    "why.ctaButton": "Get Started Today",

    // Team
    "team.badge": "Our Team",
    "team.headline": "Powered by",
    "team.headlineHighlight": "Experience",
    "team.p1": "The WINSO team has many years of experience in business and sales, as well as extensive knowledge in electrical engineering. Our combined expertise positions us uniquely to revolutionize the small wind power market.",
    "team.p2": "We plan to add more experienced professionals to the team in purchasing, sales, production, and marketing to ensure the startup's success.",
    "team.expertise": "Areas of Expertise",
    "team.exp1": "Business Strategy",
    "team.exp2": "Sales & Growth",
    "team.exp3": "Electrical Engineering",
    "team.exp4": "Purchasing",
    "team.exp5": "Marketing",
    "team.exp6": "Production",
    "team.years": "Years",
    "team.combined": "Combined",
    "team.experience": "Experience",
    "team.industries": "Industries",
    "team.mastered": "Mastered",
    "team.expanding": "Expanding Capabilities",
    "team.area1": "Purchasing & Supply Chain",
    "team.area2": "Sales & Business Development",
    "team.area3": "Production & Manufacturing",
    "team.area4": "Marketing & Brand Growth",

    // Contact
    "contact.badge": "Get in Touch",
    "contact.headline": "Ready to Power Your",
    "contact.headlineHighlight": "Future?",
    "contact.subheadline": "Whether you have questions about our turbines, need a custom quote, or just want to learn more about wind power—we're here to help.",
    "contact.person": "Contact Person",
    "contact.emailUs": "Email Us",
    "contact.callUs": "Call Us",
    "contact.thankYou": "Thank You!",
    "contact.thankYouMsg": "Your message has been sent successfully. We'll be in touch soon.",
    "contact.sendAnother": "Send Another Message",
    "contact.name": "Name",
    "contact.namePlaceholder": "Your name",
    "contact.email": "Email",
    "contact.emailPlaceholder": "you@example.com",
    "contact.subject": "Subject",
    "contact.subjectPlaceholder": "How can we help?",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us about your project...",
    "contact.sending": "Sending...",
    "contact.sendMessage": "Send Message",

    // Footer
    "footer.slogan": "Hybrid is Simply Better",
    "footer.description": "Pioneering the future of small wind power. Efficient, affordable, and designed for independent energy generation.",
    "footer.product": "Product",
    "footer.features": "Features",
    "footer.specifications": "Specifications",
    "footer.installation": "Installation",
    "footer.support": "Support",
    "footer.company": "Company",
    "footer.aboutUs": "About Us",
    "footer.ourTeam": "Our Team",
    "footer.careers": "Careers",
    "footer.contact": "Contact",
    "footer.resources": "Resources",
    "footer.documentation": "Documentation",
    "footer.faq": "FAQ",
    "footer.blog": "Blog",
    "footer.pressKit": "Press Kit",
    "footer.copyright": "WINSO Energy. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookie Policy",
  },
  de: {
    // Header
    "nav.about": "Über uns",
    "nav.product": "Produkt",
    "nav.whyWinso": "Warum WINSO",
    "nav.team": "Team",
    "nav.contact": "Kontakt",

    // Hero
    "hero.badge": "Hybrid ist einfach besser",
    "hero.headline": "WINSO –",
    "hero.headlineHighlight": "Hybrid ist einfach besser",
    "hero.subheadline": "Bei WINSO wollen wir erneuerbare Energie einfacher, intelligenter und effizienter machen. Unsere Turbine kombiniert Wind- und Solarenergie in einem Hybridsystem, das auch bei wechselnden Wetterbedingungen stabile Energie produziert.",
    "hero.learnMore": "Mehr erfahren",
    "hero.contactUs": "Kontakt",
    "hero.yearsExp": "Jahre",
    "hero.experience": "Erfahrung",
    "hero.cleanEnergy": "Saubere",
    "hero.energy": "Energie",
    "hero.designed": "Entworfen &",
    "hero.manufactured": "Hergestellt",

    // About
    "about.badge": "Über WINSO",
    "about.headline": "Technologie, die sich",
    "about.headlineHighlight": "anpasst",
    "about.p1": "Bei WINSO wollen wir erneuerbare Energie einfacher, intelligenter und effizienter machen. Unsere Turbine kombiniert Wind- und Solarenergie in einem Hybridsystem, das auch bei wechselnden Wetterbedingungen stabile Energie produziert.",
    "about.p2": "Wir glauben, dass die Zukunft der Energie in Technologie liegt, die sich anpasst und nicht wartet. Deshalb nutzt WINSO solarbetriebene Motorunterstützung, flexible Solarblätter und intelligente Steuerungssysteme, um die Leistung jederzeit hoch zu halten.",
    "about.p3": "Unsere Vision ist klar: zuverlässige saubere Energie überall liefern, mit einem System, das Tag und Nacht arbeitet — und erneuerbare Energie einen Schritt vorwärts bringt.",
    "about.feature1": "Solarbetriebene Motorunterstützung",
    "about.feature2": "Flexible Solarblätter",
    "about.feature3": "Intelligente Steuerungssysteme",
    "about.appTitle": "Perfekt für jede Anwendung",
    "about.app1": "Privathaushalte",
    "about.app2": "Gartenhäuser",
    "about.app3": "Inselanwendungen",
    "about.app4": "Ferienhäuser",
    "about.app5": "Wohnmobile",
    "about.app6": "Boote & Yachten",
    "about.appDesc1": "Versorgen Sie Ihr Zuhause mit Strom, senken Sie die Stromkosten und bleiben Sie unabhängig mit einem stabilen hybriden Wind-Solar-System.",
    "about.appDesc2": "Betreiben Sie Beleuchtung, Werkzeuge und kleine Geräte mit einem netzunabhängigen System, das seine eigene Energie erzeugt und speichert.",
    "about.appDesc3": "Bleiben Sie in abgelegenen Gebieten vollständig unabhängig mit einer Hybridturbine, die für kontinuierliche, zuverlässige Energieerzeugung ausgelegt ist.",
    "about.appDesc4": "Halten Sie Ihr Ferienhaus das ganze Jahr über mit Strom versorgt – mit einem wartungsarmen System, das bei wechselnden Bedingungen funktioniert.",
    "about.appDesc5": "Erzeugen Sie unterwegs saubere Energie mit einem kompakten System, das für Mobilität und effizientes Laden von Batterien gebaut ist.",
    "about.appDesc6": "Versorgen Sie Bordsysteme mit Wind- und Solarenergie in einer platzsparenden Hybridlösung.",

    // Product
    "product.badge": "Unsere Mission",
    "product.headline": "Die",
    "product.headlineHighlight": "WINSO",
    "product.headlineEnd": "Turbine",
    "product.intro": "Wir stellen unsere WINSO-Turbine vor — ein hybrides Wind-Solar-System, das die Leistung horizontaler Windturbinen erreicht und sogar übertrifft. Solarzellen, die direkt in die Rotorblätter integriert sind, treiben einen Elektromotor an, der zusätzlichen Antrieb liefert, ohne zusätzlichen Platz zu benötigen.",
    "product.techTitle": "Technisch durchdacht",
    "product.techP1": "Diese elektrische Unterstützung ermöglicht auch bei schwachem Wind eine kontinuierliche Energieproduktion, die bis zu 30% der Gesamtleistung beiträgt und den täglichen Energieertrag erheblich steigert.",
    "product.techP2": "Die Windblätter sind auf beweglichen Stützen montiert, die auf Fliehkräfte reagieren. Bei hohen Drehzahlen gehen sie in eine geschlossene ovale Konfiguration über, die den Windeinfluss auf die Blätter reduziert. Dies verhindert ein Übersteuern des Systems und eliminiert den Gegenwindwiderstand — für einen insgesamt sichereren und effizienteren Betrieb.",
    "product.benefit1": "Solarzellen direkt in die Rotorblätter integriert",
    "product.benefit2": "Elektromotor für kontinuierlichen Betrieb bei schwachem Wind",
    "product.benefit3": "Bewegliche Stützen verhindern gefährliches Übersteuern",
    "product.benefit4": "Geschlossene ovale Konfiguration reduziert Windeinfluss bei hohen Geschwindigkeiten",
    "product.benefit5": "Eliminiert Gegenwindwiderstand für sichereren Betrieb",
    "product.requestQuote": "Angebot anfordern",
    "product.output": "Leistung",
    "product.hybrid": "Hybrid",
    "product.technology": "Technologie",
    "product.feat1Title": "Hybrides Design",
    "product.feat1Desc": "Wind-Solar-Integration mit Solarzellen, die direkt in die Rotorblätter eingebaut sind.",
    "product.feat2Title": "Überlegene Effizienz",
    "product.feat2Desc": "Erreicht und übertrifft die Leistung horizontaler Turbinen mit elektrischer Boost-Fähigkeit.",
    "product.feat3Title": "Schwachwind-Betrieb",
    "product.feat3Desc": "Der Elektromotor liefert zusätzlichen Antrieb bei schwachem Wind für konstante Leistung.",
    "product.feat4Title": "Platzsparend",
    "product.feat4Desc": "Kein zusätzlicher Platz erforderlich — Solarintegration bedeutet alles in einer kompakten Einheit.",
    "product.feat5Title": "Kosteneffektiv",
    "product.feat5Desc": "Nicht wesentlich teurer als traditionelle vertikale Turbinen.",
    "product.feat6Title": "Intelligente Sicherheit",
    "product.feat6Desc": "Bewegliche Blattstützen verhindern Überdrehzahl und eliminieren Gegenwindwiderstand.",

    // Business Model
    "business.badge": "Geschäftsmodell",
    "business.headline": "Einfach und",
    "business.headlineHighlight": "Skalierbar",
    "business.p1": "Unser Geschäftsmodell ist einfach und skalierbar. Unser Ziel ist es, Windturbinen durch Eigenproduktion kosteneffektiv herzustellen. Die WINSO-Turbine ist nicht wesentlich teurer als eine traditionelle vertikale Turbine.",
    "business.p2": "Durch ein anfänglich schlankes Angebot können wir unser Produkt effizienter und kostengünstiger anbieten als vergleichbare Leistungsmodelle auf dem Markt. Die Fokussierung auf Einmalverkäufe ermöglicht uns stabile und wiederkehrende Einnahmen mit Wachstumspotenzial.",
    "business.pillar1Title": "Eigenproduktion",
    "business.pillar1Desc": "Kosteneffektive Produktion durch vollständige Fertigungskontrolle.",
    "business.pillar2Title": "Schlanke Produktlinie",
    "business.pillar2Desc": "Anfänglich schlankes Angebot für Effizienz und niedrigere Kosten als vergleichbare Modelle.",
    "business.pillar3Title": "Skalierbares Modell",
    "business.pillar3Desc": "Einfache Struktur, die mit der wachsenden Marktnachfrage skaliert.",
    "business.pillar4Title": "Wiederkehrende Einnahmen",
    "business.pillar4Desc": "Einmalverkäufe als Basis mit stabilen, wiederkehrenden Einnahmen und Wachstumspotenzial.",
    "business.approach": "Unser Ansatz",
    "business.costEffective": "Kosten",
    "business.effectiveProd": "Effektive",
    "business.production": "Produktion",
    "business.lean": "Schlank",
    "business.initial": "Initiales",
    "business.offering": "Angebot",

    // Why WINSO
    "why.badge": "Warum wir",
    "why.headline": "Warum",
    "why.headlineHighlight": "WINSO",
    "why.subheadline": "Wenn es um kleine Windkraft geht, liefert WINSO auf ganzer Linie. Das unterscheidet uns von der Konkurrenz.",
    "why.benefit1Title": "Maximale Effizienz",
    "why.benefit1Desc": "Unser Hybriddesign fängt mehr Windenergie ein als traditionelle Turbinen und liefert mehr Leistung aus jeder Brise.",
    "why.benefit2Title": "Langlebig gebaut",
    "why.benefit2Desc": "Mit hochwertigen Materialien und strengen Tests für 20+ Jahre zuverlässigen Betrieb entwickelt.",
    "why.benefit3Title": "Erschwingliche Exzellenz",
    "why.benefit3Desc": "Wettbewerbsfähige Preise ohne Kompromisse. Echter Wert, der sich im Laufe der Zeit auszahlt.",
    "why.benefit4Title": "Moderne Technik",
    "why.benefit4Desc": "Spitzentechnologie trifft auf praktisches Design. Intelligente Funktionen, die Ihr Leben vereinfachen.",
    "why.benefit5Title": "Expertenteam",
    "why.benefit5Desc": "Gestützt durch jahrzehntelange kombinierte Erfahrung in Wirtschaft, Vertrieb und Elektrotechnik.",
    "why.benefit6Title": "Qualität garantiert",
    "why.benefit6Desc": "Jede Turbine wird getestet und zertifiziert, um die höchsten europäischen Standards zu erfüllen.",
    "why.cta": "Bereit, Ihre Zukunft mit sauberer, effizienter Windenergie zu gestalten?",
    "why.ctaButton": "Jetzt starten",

    // Team
    "team.badge": "Unser Team",
    "team.headline": "Angetrieben von",
    "team.headlineHighlight": "Erfahrung",
    "team.p1": "Das WINSO-Team verfügt über langjährige Erfahrung in Wirtschaft und Vertrieb sowie umfassende Kenntnisse in der Elektrotechnik. Unsere kombinierte Expertise positioniert uns einzigartig, um den Markt für kleine Windkraft zu revolutionieren.",
    "team.p2": "Wir planen, weitere erfahrene Fachleute in den Bereichen Einkauf, Vertrieb, Produktion und Marketing ins Team zu holen, um den Erfolg des Startups sicherzustellen.",
    "team.expertise": "Fachbereiche",
    "team.exp1": "Geschäftsstrategie",
    "team.exp2": "Vertrieb & Wachstum",
    "team.exp3": "Elektrotechnik",
    "team.exp4": "Einkauf",
    "team.exp5": "Marketing",
    "team.exp6": "Produktion",
    "team.years": "Jahre",
    "team.combined": "Kombinierte",
    "team.experience": "Erfahrung",
    "team.industries": "Branchen",
    "team.mastered": "Gemeistert",
    "team.expanding": "Wachsende Fähigkeiten",
    "team.area1": "Einkauf & Lieferkette",
    "team.area2": "Vertrieb & Geschäftsentwicklung",
    "team.area3": "Produktion & Fertigung",
    "team.area4": "Marketing & Markenaufbau",

    // Contact
    "contact.badge": "Kontakt aufnehmen",
    "contact.headline": "Bereit, Ihre",
    "contact.headlineHighlight": "Zukunft zu gestalten?",
    "contact.subheadline": "Ob Sie Fragen zu unseren Turbinen haben, ein individuelles Angebot benötigen oder einfach mehr über Windkraft erfahren möchten — wir sind für Sie da.",
    "contact.person": "Ansprechpartner",
    "contact.emailUs": "E-Mail",
    "contact.callUs": "Anrufen",
    "contact.thankYou": "Vielen Dank!",
    "contact.thankYouMsg": "Ihre Nachricht wurde erfolgreich gesendet. Wir melden uns bald bei Ihnen.",
    "contact.sendAnother": "Weitere Nachricht senden",
    "contact.name": "Name",
    "contact.namePlaceholder": "Ihr Name",
    "contact.email": "E-Mail",
    "contact.emailPlaceholder": "sie@beispiel.com",
    "contact.subject": "Betreff",
    "contact.subjectPlaceholder": "Wie können wir helfen?",
    "contact.message": "Nachricht",
    "contact.messagePlaceholder": "Erzählen Sie uns von Ihrem Projekt...",
    "contact.sending": "Wird gesendet...",
    "contact.sendMessage": "Nachricht senden",

    // Footer
    "footer.slogan": "Hybrid ist einfach besser",
    "footer.description": "Wegbereiter der Zukunft kleiner Windkraft. Effizient, erschwinglich und für unabhängige Energieerzeugung konzipiert.",
    "footer.product": "Produkt",
    "footer.features": "Funktionen",
    "footer.specifications": "Spezifikationen",
    "footer.installation": "Installation",
    "footer.support": "Support",
    "footer.company": "Unternehmen",
    "footer.aboutUs": "Über uns",
    "footer.ourTeam": "Unser Team",
    "footer.careers": "Karriere",
    "footer.contact": "Kontakt",
    "footer.resources": "Ressourcen",
    "footer.documentation": "Dokumentation",
    "footer.faq": "FAQ",
    "footer.blog": "Blog",
    "footer.pressKit": "Presse-Kit",
    "footer.copyright": "WINSO Energy. Alle Rechte vorbehalten.",
    "footer.privacy": "Datenschutz",
    "footer.terms": "Nutzungsbedingungen",
    "footer.cookies": "Cookie-Richtlinie",
  },
  sk: {
    // Header
    "nav.about": "O nás",
    "nav.product": "Produkt",
    "nav.whyWinso": "Prečo WINSO",
    "nav.team": "Tím",
    "nav.contact": "Kontaktujte nás",

    // Hero
    "hero.badge": "Hybrid je jednoducho lepší",
    "hero.headline": "WINSO –",
    "hero.headlineHighlight": "Hybrid je jednoducho lepší",
    "hero.subheadline": "V spoločnosti WINSO sa snažíme urobiť obnoviteľnú energiu jednoduchšou, inteligentnejšou a efektívnejšou. Naša turbína kombinuje veternú a solárnu energiu do jedného hybridného systému, ktorý produkuje stabilnú energiu aj pri zmene počasia.",
    "hero.learnMore": "Zistiť viac",
    "hero.contactUs": "Kontaktujte nás",
    "hero.yearsExp": "Rokov",
    "hero.experience": "Skúseností",
    "hero.cleanEnergy": "Čistá",
    "hero.energy": "Energia",
    "hero.designed": "Navrhnuté a",
    "hero.manufactured": "Vyrobené",

    // About
    "about.badge": "O WINSO",
    "about.headline": "Technológia, ktorá sa",
    "about.headlineHighlight": "prispôsobuje",
    "about.p1": "V spoločnosti WINSO sa snažíme urobiť obnoviteľnú energiu jednoduchšou, inteligentnejšou a efektívnejšou. Naša turbína kombinuje veternú a solárnu energiu do jedného hybridného systému, ktorý produkuje stabilnú energiu aj pri zmene počasia.",
    "about.p2": "Veríme, že budúcnosť energie spočíva v technológii, ktorá sa prispôsobuje, nie čaká. Preto WINSO využíva solárnu motorovú podporu, flexibilné solárne listy a inteligentné riadiace systémy na udržanie vysokého výkonu po celý čas.",
    "about.p3": "Naša vízia je jasná: dodávať spoľahlivú čistú energiu kdekoľvek, so systémom, ktorý pracuje deň i noc — a posúva obnoviteľnú energiu o krok vpred.",
    "about.feature1": "Solárna motorová podpora",
    "about.feature2": "Flexibilné solárne listy",
    "about.feature3": "Inteligentné riadiace systémy",
    "about.appTitle": "Perfektné pre každú aplikáciu",
    "about.app1": "Súkromné domácnosti",
    "about.app2": "Záhradné domčeky",
    "about.app3": "Ostrovné aplikácie",
    "about.app4": "Rekreačné domy",
    "about.app5": "Mobilné domy",
    "about.app6": "Lode a jachty",
    "about.appDesc1": "Napájajte svoj domov, znížte náklady na elektrickú energiu a zostaňte nezávislí so stabilným hybridným veterno-solárnym systémom.",
    "about.appDesc2": "Prevádzkujte osvetlenie, nástroje a malé spotrebiče s off-grid systémom, ktorý generuje a ukladá vlastnú energiu.",
    "about.appDesc3": "Zostaňte plne nezávislí v odľahlých oblastiach s hybridnou turbínou navrhnutou pre nepretržitú, spoľahlivú výrobu energie.",
    "about.appDesc4": "Udržujte svoju dovolenkovú chatu napájanú celý rok s nenáročným systémom, ktorý funguje v meniacich sa podmienkach.",
    "about.appDesc5": "Vyrábajte čistú energiu na cestách s kompaktným systémom vytvoreným pre mobilitu a efektívne nabíjanie batérií.",
    "about.appDesc6": "Napájajte palubné systémy pomocou veternej a solárnej energie v priestorovo efektívnom hybridnom riešení.",

    // Product
    "product.badge": "Naša misia",
    "product.headline": "Turbína",
    "product.headlineHighlight": "WINSO",
    "product.headlineEnd": "",
    "product.intro": "Predstavujeme našu turbínu WINSO — hybridný veterno-solárny systém, ktorý sa vyrovná a dokonca prevyšuje výkon horizontálnych veterných turbín. Solárne články integrované priamo do lopatiek rotora poháňajú elektromotor, ktorý poskytuje dodatočný pohon, čo znamená, že nie je potrebný žiadny extra priestor.",
    "product.techTitle": "Technicky dobre premyslené",
    "product.techP1": "Táto elektrická podpora tiež umožňuje kontinuálnu výrobu energie pri slabom vetre, pričom prispieva až 30% celkového výkonu a výrazne zvyšuje denný výnos energie.",
    "product.techP2": "Veterné lopatky sú namontované na pohyblivých podperách, ktoré reagujú na odstredivé sily. Pri vysokých otáčkach prechádzajú do uzavretej oválnej konfigurácie, čím sa znižuje vplyv vetra na lopatky. To zabraňuje pretáčaniu systému a zároveň eliminuje odpor proti vetru — čím sa zabezpečuje celkovo bezpečnejšia a efektívnejšia prevádzka.",
    "product.benefit1": "Solárne články integrované priamo do lopatiek rotora",
    "product.benefit2": "Elektromotor pre nepretržitú prevádzku pri slabom vetre",
    "product.benefit3": "Pohyblivé podpery zabraňujú nebezpečnému pretáčaniu",
    "product.benefit4": "Uzavretá oválna konfigurácia znižuje vplyv vetra pri vysokých rýchlostiach",
    "product.benefit5": "Eliminuje odpor proti vetru pre bezpečnejšiu prevádzku",
    "product.requestQuote": "Požiadať o cenovú ponuku",
    "product.output": "Výkon",
    "product.hybrid": "Hybridná",
    "product.technology": "Technológia",
    "product.feat1Title": "Hybridný dizajn",
    "product.feat1Desc": "Integrácia vetra a slnka so solárnymi článkami zabudovanými priamo do lopatiek rotora.",
    "product.feat2Title": "Vynikajúca účinnosť",
    "product.feat2Desc": "Vyrovná sa a prevyšuje výkon horizontálnych turbín s možnosťou elektrického zosilnenia.",
    "product.feat3Title": "Prevádzka pri slabom vetre",
    "product.feat3Desc": "Elektromotor poskytuje dodatočný pohon pri slabom vetre pre konzistentný výkon.",
    "product.feat4Title": "Priestorovo efektívne",
    "product.feat4Desc": "Nie je potrebný žiadny extra priestor — solárna integrácia znamená všetko v jednej kompaktnej jednotke.",
    "product.feat5Title": "Nákladovo efektívne",
    "product.feat5Desc": "Nie je výrazne drahšia ako tradičné vertikálne turbíny.",
    "product.feat6Title": "Inteligentná bezpečnosť",
    "product.feat6Desc": "Pohyblivé podpery lopatiek zabraňujú pretáčaniu a eliminujú odpor proti vetru.",

    // Business Model
    "business.badge": "Obchodný model",
    "business.headline": "Jednoduchý a",
    "business.headlineHighlight": "Škálovateľný",
    "business.p1": "Náš obchodný model je jednoduchý a škálovateľný. Naším cieľom je vyrábať veterné turbíny nákladovo efektívne prostredníctvom vlastnej výroby. Turbína WINSO nie je výrazne drahšia ako tradičná vertikálna turbína.",
    "business.p2": "Prostredníctvom pôvodne úspornej ponuky môžeme náš produkt poskytovať efektívnejšie a za nižšiu cenu ako porovnateľné modely na trhu. Zameranie na jednorazový predaj nám umožňuje dosiahnuť stabilné a opakujúce sa príjmy s rastovým potenciálom.",
    "business.pillar1Title": "Vlastná výroba",
    "business.pillar1Desc": "Nákladovo efektívna výroba prostredníctvom úplnej kontroly výroby.",
    "business.pillar2Title": "Úsporná produktová línia",
    "business.pillar2Desc": "Pôvodne úsporná ponuka pre efektivitu a nižšie náklady ako porovnateľné modely.",
    "business.pillar3Title": "Škálovateľný model",
    "business.pillar3Desc": "Jednoduchá štruktúra navrhnutá na škálovanie s rastúcim dopytom na trhu.",
    "business.pillar4Title": "Opakujúce sa príjmy",
    "business.pillar4Desc": "Základ jednorazového predaja so stabilnými, opakujúcimi sa príjmami a rastovým potenciálom.",
    "business.approach": "Náš prístup",
    "business.costEffective": "Nákladovo",
    "business.effectiveProd": "Efektívna",
    "business.production": "Výroba",
    "business.lean": "Úsporná",
    "business.initial": "Počiatočná",
    "business.offering": "Ponuka",

    // Why WINSO
    "why.badge": "Prečo si nás vybrať",
    "why.headline": "Prečo si vybrať",
    "why.headlineHighlight": "WINSO",
    "why.subheadline": "Pokiaľ ide o malú veternú energiu, WINSO dodáva na všetkých frontoch. Tu je to, čo nás odlišuje od konkurencie.",
    "why.benefit1Title": "Maximálna účinnosť",
    "why.benefit1Desc": "Náš hybridný dizajn zachytáva viac veternej energie ako tradičné turbíny a poskytuje vám viac energie z každého vánku.",
    "why.benefit2Title": "Postavené na vydržanie",
    "why.benefit2Desc": "Navrhnuté s prémiovými materiálmi a prísnymi testami pre 20+ rokov spoľahlivej prevádzky.",
    "why.benefit3Title": "Dostupná excelentnosť",
    "why.benefit3Desc": "Konkurenčné ceny bez znižovania kvality. Skutočná hodnota, ktorá sa časom sama zaplatí.",
    "why.benefit4Title": "Moderné inžinierstvo",
    "why.benefit4Desc": "Špičková technológia sa stretáva s praktickým dizajnom. Inteligentné funkcie, ktoré zjednodušujú váš život.",
    "why.benefit5Title": "Expertný tím",
    "why.benefit5Desc": "Podporovaní desaťročiami kombinovaných skúseností v podnikaní, predaji a elektrotechnike.",
    "why.benefit6Title": "Zaručená kvalita",
    "why.benefit6Desc": "Každá turbína je testovaná a certifikovaná podľa najvyšších európskych štandardov.",
    "why.cta": "Ste pripravení poháňať svoju budúcnosť čistou, efektívnou veternou energiou?",
    "why.ctaButton": "Začnite ešte dnes",

    // Team
    "team.badge": "Náš tím",
    "team.headline": "Poháňaní",
    "team.headlineHighlight": "Skúsenosťami",
    "team.p1": "Tím WINSO má dlhoročné skúsenosti v podnikaní a predaji, ako aj rozsiahle znalosti v elektrotechnike. Naša kombinovaná odbornosť nás jedinečne pozicionuje na revolúciu na trhu malej veternej energie.",
    "team.p2": "Plánujeme pridať ďalších skúsených profesionálov do tímu v oblasti nákupu, predaja, výroby a marketingu, aby sme zabezpečili úspech startupu.",
    "team.expertise": "Oblasti expertízy",
    "team.exp1": "Obchodná stratégia",
    "team.exp2": "Predaj a rast",
    "team.exp3": "Elektrotechnika",
    "team.exp4": "Nákup",
    "team.exp5": "Marketing",
    "team.exp6": "Výroba",
    "team.years": "Rokov",
    "team.combined": "Kombinovaných",
    "team.experience": "Skúseností",
    "team.industries": "Odvetví",
    "team.mastered": "Zvládnutých",
    "team.expanding": "Rastúce schopnosti",
    "team.area1": "Nákup a dodávateľský reťazec",
    "team.area2": "Predaj a obchodný rozvoj",
    "team.area3": "Výroba a produkcia",
    "team.area4": "Marketing a rast značky",

    // Contact
    "contact.badge": "Spojte sa s nami",
    "contact.headline": "Pripravení poháňať vašu",
    "contact.headlineHighlight": "Budúcnosť?",
    "contact.subheadline": "Či už máte otázky o našich turbínach, potrebujete individuálnu cenovú ponuku, alebo sa chcete dozvedieť viac o veternej energii — sme tu, aby sme pomohli.",
    "contact.person": "Kontaktná osoba",
    "contact.emailUs": "Napíšte nám",
    "contact.callUs": "Zavolajte nám",
    "contact.thankYou": "Ďakujeme!",
    "contact.thankYouMsg": "Vaša správa bola úspešne odoslaná. Čoskoro sa ozveme.",
    "contact.sendAnother": "Poslať ďalšiu správu",
    "contact.name": "Meno",
    "contact.namePlaceholder": "Vaše meno",
    "contact.email": "Email",
    "contact.emailPlaceholder": "vy@priklad.sk",
    "contact.subject": "Predmet",
    "contact.subjectPlaceholder": "Ako vám môžeme pomôcť?",
    "contact.message": "Správa",
    "contact.messagePlaceholder": "Povedzte nám o vašom projekte...",
    "contact.sending": "Odosiela sa...",
    "contact.sendMessage": "Odoslať správu",

    // Footer
    "footer.slogan": "Hybrid je jednoducho lepší",
    "footer.description": "Priekopníci budúcnosti malej veternej energie. Efektívne, dostupné a navrhnuté pre nezávislú výrobu energie.",
    "footer.product": "Produkt",
    "footer.features": "Funkcie",
    "footer.specifications": "Špecifikácie",
    "footer.installation": "Inštalácia",
    "footer.support": "Podpora",
    "footer.company": "Spoločnosť",
    "footer.aboutUs": "O nás",
    "footer.ourTeam": "Náš tím",
    "footer.careers": "Kariéra",
    "footer.contact": "Kontakt",
    "footer.resources": "Zdroje",
    "footer.documentation": "Dokumentácia",
    "footer.faq": "FAQ",
    "footer.blog": "Blog",
    "footer.pressKit": "Pre médiá",
    "footer.copyright": "WINSO Energy. Všetky práva vyhradené.",
    "footer.privacy": "Ochrana súkromia",
    "footer.terms": "Podmienky služby",
    "footer.cookies": "Zásady cookies",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
